### ISSUE TITLE
((APKInfoExtractor)Session["apkInfoExtraction"]).startExtraction()    يظهر لي null عند اضاف apk 

### ISSUE THREAD

**Issue by noof42** [AmrAshraf/AndroShield#14]
عند اضاف apk 
ونقر على analyze  

((APKInfoExtractor)Session["apkInfoExtraction"]).startExtraction()
 يظهر لي null
[مشكلة.docx](https://github.com/AmrAshraf/AndroShield/files/5826762/default.docx)

**Comment by AmrAshraf** [comment]
Environment variables need to be correct. Instructions updated.
